# Generated by Django 4.1.3 on 2023-11-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='notification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=255),
        ),
    ]
